modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "picojobs"
version = "${version}"
displayName = "PicoJobs"
authors = "Picono435"
description = '''
@description@
'''
#logoFile = ""

[[dependencies.picojobs]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picojobs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picojobs]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"