import org.apache.tools.ant.filters.*

plugins {
    id 'com.gradleup.shadow' version '8.3.6'
    id 'java-library'
    id 'maven-publish'
    id 'net.nemerosa.versioning' version '3.1.0'
    id 'signing'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

if (System.getenv("STABLE_BUILD") == '0') {
    rootProject.version = versioning.info.build + "-DEV"
} else {
    rootProject.version = "1.0-pre-1"
}

subprojects {
    apply plugin: 'com.gradleup.shadow'
    apply plugin: 'signing'
    apply plugin: 'base'

    repositories {
        maven {
            name = "PiconoDev Repository"
            url = uri("https://repo.piconodev.com/repository/maven-snapshots")
        }
    }


    shadowJar {
        archiveBaseName.set(rootProject.archives_base_name)
        archiveVersion.set(rootProject.version)
        configurations = [project.configurations.shadow]
    }

    tasks.withType(com.gradleup.shadow.tasks.ShadowJar).configureEach {
        relocate 'org.spongepowered.configurate', 'com.gmail.picono435.picojobs.libs.org.spongepowered.configurate'
        relocate 'com.google.common', 'com.gmail.picono435.picojobs.libs.com.google.common'
        relocate 'com.google.errorprone', 'com.gmail.picono435.picojobs.libs.com.google.errorprone'
        relocate 'com.google.gson', 'com.gmail.picono435.picojobs.libs.com.google.gson'
        relocate 'com.google.j2objc', 'com.gmail.picono435.picojobs.libs.com.google.j2objc'
        relocate 'com.google.thirdparty', 'com.gmail.picono435.picojobs.libs.com.google.thirdparty'
        relocate 'com.typesafe.config', 'com.gmail.picono435.picojobs.libs.com.typesafe.config'
        relocate 'io.github.slimjar', 'com.gmail.picono435.picojobs.libs.io.github.slimjar'
        relocate 'io.leangen.geantyref', 'com.gmail.picono435.picojobs.libs.io.github.geantyref'
        relocate 'javax.annotation', 'com.gmail.picono435.picojobs.libs.javax.annotation'
        relocate 'org.apache.commons', 'com.gmail.picono435.picojobs.libs.org.apache.commons'
        relocate 'org.apache.maven.artifact', 'com.gmail.picono435.picojobs.libs.org.apache.maven.artifact'
        relocate 'org.apache.maven.repository', 'com.gmail.picono435.picojobs.libs.org.apache.maven.repository'
        relocate 'org.checkerframework', 'com.gmail.picono435.picojobs.libs.org.checkerframework'
        relocate 'org.codehaus.plexus', 'com.gmail.picono435.picojobs.libs.org.codehaus.plexus'
        relocate 'org.yaml.snakeyaml', 'com.gmail.picono435.picojobs.libs.org.yaml.snakeyaml'
    }

    tasks.withType(JavaExec).configureEach {
        systemProperty("bstats.relocatecheck", "false")
    }

    /*signing {
        useGpgCmd()
        sign configurations.shadow
    }*/
}

allprojects {
    apply plugin: 'java-library'
    apply plugin: 'signing'

    base {
        archivesName = rootProject.archives_base_name
    }
    version = rootProject.version
    group = rootProject.group
    description = rootProject.description

    task sourcesJar(type: Jar, dependsOn: classes) {
        archiveClassifier.set('sources')
        from sourceSets.main.allSource
    }

    artifacts {
        archives sourcesJar
    }

    processResources {
        filter ReplaceTokens, tokens: [
                "name": rootProject.property("name"),
                "version": rootProject.property("version"),
                "description": rootProject.property("description")
        ]
    }
}



publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = 'picojobs'
            version = project.version
            from components.java

            pom {
                name = "PicoJobs"
                description = "An amazing plugin that allows you to create your own jobs for your players. The plugin is 100% configurable so you can change everything you see, it is also open-source if you want to take a look on how it's made."
                url = "https://github.com/Picono435/PicoJobs"
                licenses {
                    license {
                        name = "The MIT License"
                        url = "https://opensource.org/licenses/MIT"
                    }
                }
                developers {
                    developer {
                        id = "picono435"
                        name = "Picono435"
                        email = "picono435@gmail.com"
                    }
                }
                scm {
                    connection = "https://github.com/Picono435/PicoJobs"
                    developerConnection = "https://github.com/Picono435/PicoJobs.git"
                    url = "https://github.com/Picono435/PicoJobs"
                }
            }
        }
    }
    repositories {
        maven {
            credentials {
                username = System.getenv("REPO_USER")
                password = System.getenv("REPO_PASSWORD")
            }

            url = uri('https://repo.piconodev.com/repository/maven-releases/')
        }
    }
}
