pluginManagement {
    repositories {
        maven { url = uri("https://maven.architectury.dev/") }
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://maven.minecraftforge.net/") }
        maven { url = uri("https://repo.piconodev.com/repository/maven-snapshots") }
        maven { url = uri("https://jitpack.io") }
        gradlePluginPortal()
    }
}

rootProject.name = 'PicoJobs'

include("common")
include("bukkit")

