#name, main, version and api are required
name: @name@
main: com.gmail.picono435.picojobs.nukkit.PicoJobsNukkit
load: STARTUP
version: "@version@"
api: ["1.0.5"]
author: Picono435
description: @description@
website: https://piconodev.com
# These dependencies are required for the plugin to start.
#depend: ["OtherPlugin", "ThisPlugin"]
# These dependencies are not required.
softdepend: ["PlaceholderAPI", "FakeInventories"]

commands:
  jobs:
    description: Basic main command of PicoJobs
    usage: "/jobs"
    aliases: [picojobs, piconojobs, job, empregos, emprego, picoempregos, piconoempregos]
  jobsadmin:
    description: Basic admin command of PicoJobs
    usage: "/jobsadmin"
    aliases: [picojobsadmin, piconojobsadmin, jobadmin, empregosadmin, empregoadmin, picoempregosadmin, piconoempregosadmin]
permissions:
  picojobs.use.basic:
    description: "Allow you to use the basics of the /jobs command"
    default: true
  picojobs.admin:
    description: "Allow you to use the /jobsadmin command"
    default: op