#name, main, version and api are required
name: @name@
main: com.gmail.picono435.picojobs.nukkit.PicoJobsNukkit
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "@version@"
api: ["1.0.5"]
author: Picono435
description: @description@
website: https://piconodev.com
# These dependencies are required for the plugin to start.
#depend: ["OtherPlugin", "ThisPlugin"]
# These dependencies are not required.
softdepend: ["PlaceholderAPI", "FakeInventories"]

commands:
  example:
    description: Example command
    usage: "/example"
    aliases: ["xample", "nukkitexample"]
    permission: exampleplugin.command.example
    permission-message: "You do not have the required permission to run /example"
permissions:
  picojobs.use.basic:
    description: "Allow you to use the basics of the /jobs command"
    default: true
  picojobs.admin:
    description: "Allow you to use the /jobsadmin command"
    default: op