java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()

    maven {
        url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/')

        content {
            includeGroup 'org.bukkit'
            includeGroup 'org.spigotmc'
        }
    }

    maven {
        url = uri('https://jitpack.io')

        content {
            includeGroupByRegex "com\\.github.*"
        }
    }

    maven {
        url = uri('https://repo.papermc.io/repository/maven-public/')

        content {
            includeGroup 'com.github.seeseemelk'
            includeGroup 'io.papermc.paper'
            includeGroup 'net.md-5'
        }
    }

    maven {
        url = uri('https://repo.extendedclip.com/content/repositories/placeholderapi/')

        content {
            includeGroupByRegex "me\\.clip.*"
        }
    }

    maven {
        url = uri('https://repo.rosewooddev.io/repository/public/')

        content {
            includeGroupByRegex "org\\.black_ixx.*"
        }
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")

        content {
            includeGroupByRegex "com\\.sk89q.*"
            includeGroupByRegex "org\\.enginehub.*"
        }
    }

    maven {
        url = uri('https://repo.glaremasters.me/repository/bloodshot')

        content {
            includeGroup 'com.griefdefender'
        }
    }

    maven {
        url = uri('https://repo.glaremasters.me/repository/towny/')

        content {
            includeGroup 'com.palmergames.bukkit.towny'
        }
    }
}

dependencies {
    shadow implementation(project(':common'))
    compileOnly("org.spigotmc:spigot-api:${rootProject.minecraft_version}-R0.1-SNAPSHOT")
    compileOnly('me.clip:placeholderapi:2.11.6') { transitive = false }
    compileOnly('com.github.MilkBowl:VaultAPI:1.7.1') { transitive = false }
    compileOnly('org.black_ixx:playerpoints:3.2.5') { transitive = false }
    compileOnly('com.github.Realizedd:TokenManager:3.2.4') { transitive = false }
    compileOnly('com.github.TechFortress:GriefPrevention:16.18.1') { transitive = false }
    compileOnly('com.griefdefender:api:2.1.0-SNAPSHOT') { transitive = false }
    compileOnly('com.palmergames.bukkit.towny:towny:0.99.0.0') { transitive = false }
    compileOnly('org.apache.commons:commons-lang3:3.12.0')
    shadow implementation('org.bstats:bstats-bukkit:3.0.2')
}

shadowJar {
    archiveClassifier.set("bukkit")

    relocate 'org.bstats', 'com.gmail.picono435.picojobs.libs.org.bstats'
}

evaluationDependsOn(':common')

assemble.dependsOn shadowJar