package com.gmail.picono435.picojobs.menu;

public enum ActionEnum {
	
	SETDISPLAYNAME(),
	SETSALARY(),
	SETJOBTYPE(),
	SETECONOMY(),
	SETREQMETHOD(),
	SETSALARYFREQ(),
	SETWHITELIST(),
	SETMETHODFREQ(),
	
	RENAMEITEM(),
	SETLOREITEM(),
	SETACTIONITEM();
}
