name: Development Builds

on:
  push:
    branches-ignore:
      - translations

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Tests with Gradle
        env:
          STABLE_BUILD: 1
        run: |
          ls
          ./gradlew test
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Build with Gradle
        env:
          STABLE_BUILD: 0
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Builds
          path: |
            sbukkit/build/libs/*-bukkit.jar
            fabric/build/libs/*-fabric.jar
            forge/build/libs/*-forge.jar
            quilt/build/libs/*-quilt.jar
            nukkit/build/libs/*-nukkit.jar
            sponge/build/libs/*-sponge.jar
      - name: Stop The Gradle
        run: ./gradlew --stop
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/architectury
            ~/.gradle/loom-cache
            ~/.gradle/8.2.1
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-