name: Development Builds

on:
  push:
    branches-ignore:
      - translations

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - '8'
          - '11'
          - '16'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish slimJar to maven local
        run: |
         cd slimjar
         ../gradlew publishToMavenLocal
      - name: Tests with Gradle
        run: |
          ./gradlew test
           ls
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v1
        if: >
          always() &&
          github.event.sender.login != 'dependabot[bot]' &&
          ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload Artifact
        if: matrix.java-version == '8'
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Builds
          path: build/libs/*.jar
