# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unofficial Builds

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        java-version:
          - '8'
          - '11'
          - '16'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests with Gradle
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew shadowJar
      
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ github.token }}
    - name: Upload Artifact
      if: matrix.java-version == '8'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Builds
        path: build/libs/*.jar
