# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unofficial Builds

on: []

jobs:
  build-java16:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew shadowJar
      if: always()
      with:
        files: build/test-results/**/*.xml

  build-java11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew shadowJar
      if: always()
      with:
        files: build/test-results/**/*.xml

  build-java8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew shadowJar
      if: always()
      with:
        files: build/test-results/**/*.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Builds
        path: build/libs/*.jar
